name: NajdiraVortaro
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: Sam <samofcorinth@gmx.ca>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  angular: ^5.3.0
  angular_components: ^0.13.0+1
  angular_router: ^2.0.0-alpha+22
  http: ^0.12.0+2
  stream_transform: ^0.0.19

dev_dependencies:
  angular_test: ^2.2.0
  build_runner: ^1.6.1
  build_test: ^0.10.3
  build_web_compilers: ^1.0.0
  pedantic: ^1.0.0
  sass_builder: ^2.1.3
  test: ^1.5.1